/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Camel.view;

/**
 *
 * @author Jonny Dam
 */
public class PostionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoisitionJPanel
     */
    public PostionJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_search_12 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_12 = new javax.swing.JTable();
        jButton_Refresh_12 = new javax.swing.JButton();
        jButton_Add_12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_Del_12 = new javax.swing.JButton();
        jLabel_DpScreen_12 = new javax.swing.JLabel();

        jLabel1.setText("Search");

        jTextField_search_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_search_12ActionPerformed(evt);
            }
        });
        jTextField_search_12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_12KeyReleased(evt);
            }
        });

        jTable_12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_12);

        jButton_Refresh_12.setText("Refresh");
        jButton_Refresh_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Refresh_12ActionPerformed(evt);
            }
        });

        jButton_Add_12.setBackground(new java.awt.Color(40, 133, 55));
        jButton_Add_12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_12.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_12.setText("ADD");
        jButton_Add_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_12ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(25, 114, 219));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_Del_12.setBackground(new java.awt.Color(237, 74, 74));
        jButton_Del_12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Del_12.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Del_12.setText("DELETE");
        jButton_Del_12.setPreferredSize(new java.awt.Dimension(80, 21));
        jButton_Del_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Del_12ActionPerformed(evt);
            }
        });

        jLabel_DpScreen_12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_DpScreen_12.setText("Postion Screen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DpScreen_12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Add_12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Del_12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_search_12, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_Refresh_12))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel_DpScreen_12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_search_12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Refresh_12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Del_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_search_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_search_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_search_12ActionPerformed

    private void jTextField_search_12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_12KeyReleased
//        searchTable(jTextField_search_12.getText());
    }//GEN-LAST:event_jTextField_search_12KeyReleased

    private void jButton_Refresh_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Refresh_12ActionPerformed
//        DepartmentService departmentService;
//        departmentService = new DepartmentService();
//        try {
//            refreshTableData(departmentService.getAllDepartment());
//        } catch (SQLException ex) {
//            Logger.getLogger(DepartmentJPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton_Refresh_12ActionPerformed

    private void jButton_Add_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_12ActionPerformed

//        new Department_Add().setVisible(true);
    }//GEN-LAST:event_jButton_Add_12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        DefaultTableModel tblModel = (DefaultTableModel) jTable_12.getModel();
//        int id = Integer.parseInt(tblModel.getValueAt(jTable_12.getSelectedRow(), 0).toString());
//        System.out.println(id);
//        new Department_Edit(id).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_Del_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Del_12ActionPerformed
//        DefaultTableModel tblModel = (DefaultTableModel) jTable_12.getModel();
//        int id = Integer.parseInt(tblModel.getValueAt(jTable_12.getSelectedRow(), 0).toString());
//        try {
//            departmentService.deleteDepartment(id);
//        } catch (SQLException ex) {
//            Logger.getLogger(DepartmentJPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton_Del_12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Add_12;
    private javax.swing.JButton jButton_Del_12;
    private javax.swing.JButton jButton_Refresh_12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_DpScreen_12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_12;
    private javax.swing.JTextField jTextField_search_12;
    // End of variables declaration//GEN-END:variables
}
